version: 2.1
orbs:
  node: circleci/node@4.0.0

jobs:
  build-react-application:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10

    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/repo
      - run:
          name: Build react application
          command: |
            npm run-script build

workflows:
  version: 2
  build-and-test-react-application:
    jobs:
      - build-react-application
